name: Gradr

on:
  pull_request:
    branches:
    - master

jobs:
  lint: 
    name: audit code-style
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add eslint@^6.8.0 eslint-plugin-import@^2.20.1 eslint-config-airbnb-base@^14.0.0
        
    - name: Run Audits
      run: yarn eslint ./src/

  ch-1:
    needs: lint
    name: audit challenge 1
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest @babel/core @babel/preset-env babel-jest axios on-covid-19 @actions/core @actions/github
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits

    - name: Run Audits
      run: npx jest audits/ch-1 --json --outputFile=audits/ch-1.json --noStackTrace

    - name: Report Audit Stats
      uses: ./.github/actions/ch-1
      if: always()
  
  ch-2:
    needs: ch-1
    name: audit challenge 2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest @babel/core @babel/preset-env babel-jest axios on-covid-19 @actions/core @actions/github
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits

    - name: Run Audits
      run: npx jest audits/ch-2 --json --outputFile=audits/ch-2.json --noStackTrace

    - name: Report Audit Stats
      uses: ./.github/actions/ch-2
      if: always()

  ch-3:
    needs: ch-2
    name: audit challenge 3
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Prepare To Install
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Deps
      run: |
        yarn install
        yarn add jest @babel/core @babel/preset-env babel-jest axios on-covid-19 @actions/core @actions/github
    - name: Prepare Audits
      uses: actions/checkout@v2
      with: 
        repository: BuildforSDG-Cohort1-Assessment/covid-19-estimator-audits-js
        path: audits

    - name: Run Audits
      run: npx jest audits/ch-3 --json --outputFile=audits/ch-3.json --noStackTrace

    - name: Report Audit Stats
      uses: ./.github/actions/ch-3
      if: always()